spring:
  application:
    name: microservice-consumer-movie
server:
  port: 7901
user:
  userServicePath: http://localhost:7900/simaple/
  
eureka:
  client:
    serviceUrl: 
      defaultZone: http://user:123456@localhost:8761/eureka
    
  instanse:
    prefer-id-address: true
   