spring:
  application:
    name: microservice-consumer-ribbon-hystrix
server:
  port: 8040
  
eureka:
  client:
    serviceUrl: 
      defaultZone: http://user:123456@localhost:8761/eureka
    
  instanse:
    prefer-id-address: true
   