spring:
  application:
    name: microservice-consumer-ribbon-hystrix2
server:
  port: 8021
eureka:
  client:
    serviceUrl: 
      defaultZone: http://user:123456@localhost:8761/eureka
  instanse:
    prefer-id-address: true
   