spring:
  application:
    name: microservice-gateway-zuul-filter
server:
  port: 9030
eureka:
  client:
    service-url: 
      defaultZone: http://user:123456@localhost:8761/eureka
  instanse:
    prefer-id-address: true
# serviceId与url 方式路由转发请求user微服务
zuul: 
  routes: 
    test: 
      path: /user-path/** # 请求转发到serviceId
      serviceId: microservice-provider-user
#       url: http://10.100.50.26:7900/