spring:
  application:
    name: microservice-gateway-zuul
server:
  port: 9010
eureka:
  client:
    service-url: 
      defaultZone: http://user:123456@localhost:8761/eureka
  instanse:
    prefer-id-address: true
# 文件上传：设置zuul默认上传的时间限制
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000