spring:
  application:
    name: microservice-consumer-ribbon-without-eureka
server:
  port: 8060
  
eureka:
  client:
    serviceUrl: 
      defaultZone: http://user:123456@localhost:8761/eureka
  instanse:
    prefer-id-address: true
ribbon:
  eureka:
   enabled: false
#   访问user微服务
microservice-provider-user:
  ribbon:
    listOfServers: localhost:7900