spring:
  application:
    name: microservice-consumer-ribbon-properties
server:
  port: 8050
  
eureka:
  client:
    serviceUrl: 
      defaultZone: http://user:123456@localhost:8761/eureka
    
  instanse:
    prefer-id-address: true
    
#配置microservice-provider-user微服务,这里我们使用RandomRule实现负载均衡
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule