spring:
  application:
    name: microservice-consumer-feign-hystrix
server:
  port: 7040
  
eureka:
  client:
    serviceUrl: 
      defaultZone: http://user:123456@localhost:8761/eureka  
  instanse:
    prefer-id-address: true
feign:
  hystrix:
    enabled: true # To disable Hystrix in Feign
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
#        errorDecoder: com.example.SimpleErrorDecoder
#        retryer: com.example.SimpleRetryer
#        requestInterceptors:
#          - com.example.FooRequestInterceptor
#          - com.example.BarRequestInterceptor
#        decode404: false
