spring:
  application:
    name: microservice-discovery-eureka
server:
  port: 8761
security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456
eureka:
  environment: dev
  datacenter: cloud
  client:
    register-with-eureka: false
    fetch-register: false
    service-url: 
      defaultZone: http://user:123456@localhost:8761/eureka
    healthcheck:
      enabled: true

# 自定义路径
#  dashboard:
#    enabled: true
#    path: /x